// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3199keJUPn8UuPnIg6PyBQtmgQV4ul7U',
    appId: '1:446593438820:web:d44f7be4b71c31fa0bbb71',
    messagingSenderId: '446593438820',
    projectId: 'tracking-portal-eab05',
    authDomain: 'tracking-portal-eab05.firebaseapp.com',
    storageBucket: 'tracking-portal-eab05.firebasestorage.app',
    measurementId: 'G-8KJDYKQPMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP0Q9__D9CK7Q4jOv6B24CwlHORyWqzAk',
    appId: '1:446593438820:android:d08d196b62d3fc4a0bbb71',
    messagingSenderId: '446593438820',
    projectId: 'tracking-portal-eab05',
    storageBucket: 'tracking-portal-eab05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkDuQWxuIjit_VQOZZp_B_je5qH7PV59M',
    appId: '1:446593438820:ios:41e9bffdc1886a020bbb71',
    messagingSenderId: '446593438820',
    projectId: 'tracking-portal-eab05',
    storageBucket: 'tracking-portal-eab05.firebasestorage.app',
    iosBundleId: 'com.example.internalIssueTrackingPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkDuQWxuIjit_VQOZZp_B_je5qH7PV59M',
    appId: '1:446593438820:ios:41e9bffdc1886a020bbb71',
    messagingSenderId: '446593438820',
    projectId: 'tracking-portal-eab05',
    storageBucket: 'tracking-portal-eab05.firebasestorage.app',
    iosBundleId: 'com.example.internalIssueTrackingPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3199keJUPn8UuPnIg6PyBQtmgQV4ul7U',
    appId: '1:446593438820:web:c5ca3c9ba35efeb00bbb71',
    messagingSenderId: '446593438820',
    projectId: 'tracking-portal-eab05',
    authDomain: 'tracking-portal-eab05.firebaseapp.com',
    storageBucket: 'tracking-portal-eab05.firebasestorage.app',
    measurementId: 'G-1R7CP7FYL9',
  );
}
